import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Clapperboard, Film, Gauge, HeartHandshake, Library, ListVideo, LogOut, Menu, Play, Search, Settings, Shield, Ticket, Users } from 'lucide-react'

type User = { id:number; discord_id:string; username:string; global_name?:string; avatar?:string; role:'SuperAdmin'|'Admin'|'Support'|'Member'; status:string }
type Movie = { id:number; title:string; year?:number; poster_url?:string; backdrop_url?:string; genres:string[]; qualities:string[]; summary?:string; duration_ms?:number; rating?:string; actors?:string[]; directors?:string[]; media?:Array<Record<string,unknown>> }

async function api<T>(path:string, init?:RequestInit):Promise<T> {
  const response = await fetch(path, { credentials:'include', headers:{'Content-Type':'application/json', ...(init?.headers||{})}, ...init })
  if (!response.ok) {
    const body = await response.json().catch(()=>({detail:`HTTP ${response.status}`}))
    throw new Error(body.detail || `HTTP ${response.status}`)
  }
  return response.status === 204 ? (undefined as T) : response.json()
}

function Login() {
  const [params] = useSearchParams()
  const error = params.get('error')
  return <div className="login">
    <div className="login-art"><div className="brand">PLUMBUS<span> // CINEMA</span></div><h2 style={{fontSize:'clamp(42px,6vw,90px)',lineHeight:.9,margin:0,letterSpacing:'-.055em'}}>Private cinema.<br/>Plex powered.<br/>VRChat ready.</h2><p className="muted" style={{maxWidth:600}}>A controlled catalogue and playback gateway that keeps Plex credentials behind the server.</p></div>
    <div className="login-panel"><div className="login-box"><span className="badge">Private access</span><h1>Sign in</h1><p className="muted">Existing members authenticate with Discord. New accounts require an invitation URL.</p>{error && <p className="badge bad" style={{margin:'14px 0'}}>{error === 'invite_required' ? 'Registration is invite-only. Please request an invitation.' : 'This Discord account is already registered. Use normal login.'}</p>}<a className="btn primary" style={{width:'100%',marginTop:18,padding:12}} href="/api/auth/discord/login">Continue with Discord</a></div></div>
  </div>
}

function InvitePage() {
  const {token=''} = useParams(); const [state,setState]=useState<{loading:boolean;data?:any;error?:string}>({loading:true})
  useEffect(()=>{ api(`/api/invites/${encodeURIComponent(token)}/status`).then(data=>setState({loading:false,data})).catch(e=>setState({loading:false,error:e.message})) },[token])
  return <div className="login"><div className="login-art"><div className="brand">PLUMBUS<span> // INVITE</span></div><h2 style={{fontSize:'clamp(42px,6vw,82px)',lineHeight:.92,margin:0,letterSpacing:'-.05em'}}>Your seat<br/>is reserved.</h2></div><div className="login-panel"><div className="login-box"><span className="badge">Invitation</span><h1>Join Plumbus</h1>{state.loading ? <div className="skeleton" style={{height:90}}/> : state.error ? <p className="badge bad">{state.error}</p> : <><p className="muted">You have been invited to join as <strong>{state.data.assigned_role}</strong>. Discord will identify your account; the invite does not log you in directly.</p><a className="btn primary" style={{width:'100%',marginTop:18,padding:12}} href={state.data.continue_url}>Continue with Discord</a></>}</div></div></div>
}

function Shell({user,children}:{user:User;children:ReactNode}) {
  const navigate=useNavigate(); const admin=['SuperAdmin','Admin','Support'].includes(user.role)
  async function logout(){ await api('/api/auth/logout',{method:'POST'}); navigate('/login') }
  return <div className="shell"><aside className="sidebar"><div className="brand">PLUMBUS<span> // CINEMA</span></div><div className="nav-group"><div className="nav-label">Cinema</div><NavLink className="nav-link" to="/browse"><Film size={17}/>Browse</NavLink><NavLink className="nav-link" to="/search"><Search size={17}/>Search</NavLink><NavLink className="nav-link" to="/collections"><Library size={17}/>Collections</NavLink></div>{admin&&<div className="nav-group"><div className="nav-label">Operations</div><NavLink className="nav-link" to="/admin"><Gauge size={17}/>Dashboard</NavLink>{user.role!=='Support'&&<><NavLink className="nav-link" to="/admin/users"><Users size={17}/>Users</NavLink><NavLink className="nav-link" to="/admin/invites"><Ticket size={17}/>Invitations</NavLink></>}<NavLink className="nav-link" to="/admin/plex"><ListVideo size={17}/>Plex & Scans</NavLink><NavLink className="nav-link" to="/admin/logs"><Shield size={17}/>Logs</NavLink></div>}</aside><main className="main"><header className="topbar"><div style={{display:'flex',alignItems:'center',gap:10}}><button className="btn mobile-menu"><Menu size={16}/></button><strong>{user.global_name||user.username}</strong><span className="badge">{user.role}</span></div><button className="btn" onClick={logout}><LogOut size={15}/>Sign out</button></header>{children}</main></div>
}

function Browse() {
  const [movies,setMovies]=useState<Movie[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState('')
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);api<{items:Movie[]}>(`/api/movies?q=${encodeURIComponent(q)}`).then(r=>setMovies(r.items)).finally(()=>setLoading(false))},250);return()=>clearTimeout(timer)},[q])
  return <div className="page"><div className="hero"><div><span className="badge">Plex catalogue</span><h1>Tonight's library.</h1><p className="muted" style={{maxWidth:620}}>Browse indexed media, inspect codecs and create temporary playback links without exposing Plex authentication.</p><div style={{maxWidth:520,marginTop:22}}><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, actor, director, genre, collection…"/></div></div></div><div className="section-head"><div><h2>{q?'Search results':'Recently added'}</h2><div className="muted" style={{fontSize:12,marginTop:4}}>{movies.length} titles</div></div></div>{loading?<div className="poster-grid">{Array.from({length:12}).map((_,i)=><div className="poster skeleton" key={i}/>)}</div>:<PosterGrid movies={movies}/>}</div>
}

function PosterGrid({movies}:{movies:Movie[]}) { return <div className="poster-grid">{movies.map(movie=><NavLink className="poster-card" to={`/movie/${movie.id}`} key={movie.id}><div className="poster">{movie.poster_url?<img src={movie.poster_url} alt=""/>:<div className="poster-empty"><Clapperboard/><span>{movie.title}</span></div>}</div><div className="poster-title">{movie.title}</div><div className="poster-meta">{movie.year||'—'} {movie.qualities?.length?` • ${movie.qualities.join(' / ')}`:''}</div></NavLink>)}</div> }

function MovieDetail() {
  const {id}=useParams(); const [movie,setMovie]=useState<Movie|null>(null); const [play,setPlay]=useState<any>(null); const [error,setError]=useState('')
  useEffect(()=>{api<Movie>(`/api/movies/${id}`).then(setMovie).catch(e=>setError(e.message))},[id])
  async function createPlayback(){try{setPlay(await api(`/api/playback/movies/${id}`,{method:'POST'}))}catch(e:any){setError(e.message)}}
  if(error&&!movie)return <div className="page"><span className="badge bad">{error}</span></div>; if(!movie)return <div className="page"><div className="skeleton" style={{height:500}}/></div>
  const hours=movie.duration_ms?Math.floor(movie.duration_ms/3600000):0, mins=movie.duration_ms?Math.round((movie.duration_ms%3600000)/60000):0
  return <div className="detail" style={movie.backdrop_url?{backgroundImage:`url(${movie.backdrop_url})`}:{}}><div className="detail-content"><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}><span className="badge">{movie.year}</span>{movie.rating&&<span className="badge">★ {movie.rating}</span>}{movie.qualities?.map(q=><span className="badge" key={q}>{q}</span>)}</div><h1>{movie.title}</h1><p className="muted" style={{fontSize:16,lineHeight:1.7,maxWidth:760}}>{movie.summary}</p><p className="muted">{hours?`${hours}h `:''}{mins}m {movie.genres?.length?` • ${movie.genres.join(', ')}`:''}</p><div style={{display:'flex',gap:10,marginTop:24,flexWrap:'wrap'}}><button className="btn primary" onClick={createPlayback}><Play size={16}/>Generate playback URL</button></div>{play&&<div className="panel" style={{marginTop:20,padding:16,maxWidth:760}}><div className="label">Temporary URL — expires {new Date(play.expires_at).toLocaleString()}</div><input className="input" readOnly value={play.playback_url} onFocus={e=>e.currentTarget.select()}/><div style={{display:'flex',gap:8,marginTop:10}}><button className="btn" onClick={()=>navigator.clipboard.writeText(play.playback_url)}>Copy URL</button><a className="btn" href={play.playback_url}>Open stream</a></div></div>}</div></div>
}

function AdminDashboard() {
  const [users,setUsers]=useState<any[]>([]),[invites,setInvites]=useState<any[]>([]),[scans,setScans]=useState<any[]>([])
  useEffect(()=>{Promise.allSettled([api<any[]>('/api/admin/users'),api<any[]>('/api/admin/invites'),api<any[]>('/api/plex/scans')]).then(([u,i,s])=>{if(u.status==='fulfilled')setUsers(u.value);if(i.status==='fulfilled')setInvites(i.value);if(s.status==='fulfilled')setScans(s.value)})},[])
  const activeInvites=invites.filter(x=>x.status==='Active').length
  return <div className="page"><div className="section-head"><div><h2>Operations dashboard</h2><div className="muted">Users, access, Plex and playback health.</div></div></div><div className="grid-stats"><div className="stat"><span className="muted">Users</span><strong>{users.length}</strong></div><div className="stat"><span className="muted">Active invitations</span><strong>{activeInvites}</strong></div><div className="stat"><span className="muted">Scans</span><strong>{scans.length}</strong></div><div className="stat"><span className="muted">Last scan</span><strong style={{fontSize:16}}>{scans[0]?.status||'None'}</strong></div></div><div className="section-head"><h2>Recent scan activity</h2></div><ScanTable scans={scans}/></div>
}

function InviteAdmin({user}:{user:User}) {
  const [rows,setRows]=useState<any[]>([]),[created,setCreated]=useState<any>(null),[error,setError]=useState(''); const [form,setForm]=useState({label:'',expires_in_minutes:1440,max_uses:1,assigned_role:'Member'})
  const load=()=>api<any[]>('/api/admin/invites').then(setRows).catch(e=>setError(e.message)); useEffect(()=>{void load()},[])
  async function submit(e:FormEvent){e.preventDefault();try{const result=await api('/api/admin/invites',{method:'POST',body:JSON.stringify(form)});setCreated(result);load()}catch(e:any){setError(e.message)}}
  async function revoke(id:number){await api(`/api/admin/invites/${id}/revoke`,{method:'POST'});load()}
  return <div className="page"><div className="section-head"><div><h2>Invitations</h2><div className="muted">Raw tokens are only returned when an invite is created.</div></div></div><div className="split"><div className="panel"><div className="panel-head"><strong>Invitation history</strong></div><div className="table-wrap"><table><thead><tr><th>Label</th><th>Role</th><th>Uses</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.label||`Invite #${x.id}`}</td><td>{x.assigned_role}</td><td>{x.use_count}/{x.max_uses??'∞'}</td><td>{x.expires_at?new Date(x.expires_at).toLocaleString():'Never'}</td><td><span className={`badge ${x.status==='Active'?'good':x.status==='Revoked'?'bad':'warn'}`}>{x.status}</span></td><td>{x.status==='Active'&&<button className="btn danger" onClick={()=>revoke(x.id)}>Revoke</button>}</td></tr>)}</tbody></table></div></div><form className="panel" onSubmit={submit}><div className="panel-head"><strong>Create invitation</strong></div><div style={{padding:18}}><label className="label">Label</label><input className="input" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/><div className="form-grid" style={{marginTop:14}}><div><label className="label">Expires</label><select className="select" value={form.expires_in_minutes} onChange={e=>setForm({...form,expires_in_minutes:Number(e.target.value)})}><option value={60}>1 hour</option><option value={360}>6 hours</option><option value={1440}>24 hours</option><option value={4320}>3 days</option><option value={10080}>7 days</option><option value={43200}>30 days</option></select></div><div><label className="label">Maximum uses</label><select className="select" value={form.max_uses} onChange={e=>setForm({...form,max_uses:Number(e.target.value)})}>{[1,5,10,25].map(x=><option key={x}>{x}</option>)}</select></div></div><label className="label" style={{marginTop:14}}>Role</label><select className="select" value={form.assigned_role} onChange={e=>setForm({...form,assigned_role:e.target.value})}><option>Member</option><option>Support</option>{user.role==='SuperAdmin'&&<option>Admin</option>}</select><button className="btn primary" style={{width:'100%',marginTop:16}}>Create secure invite</button>{error&&<p className="badge bad">{error}</p>}{created&&<div style={{marginTop:16}}><label className="label">Copy now — token cannot be recovered later</label><input className="input" readOnly value={created.invite_url} onFocus={e=>e.currentTarget.select()}/><button type="button" className="btn" style={{marginTop:8}} onClick={()=>navigator.clipboard.writeText(created.invite_url)}>Copy Invite</button></div>}</div></form></div></div>
}

function UsersAdmin() {
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''); const load=()=>api<any[]>('/api/admin/users').then(setRows).catch(e=>setError(e.message)); useEffect(()=>{void load()},[])
 async function status(id:number,value:string){try{await api(`/api/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status:value})});load()}catch(e:any){setError(e.message)}}
 return <div className="page"><div className="section-head"><div><h2>Users</h2><div className="muted">Discord-linked identities and account state.</div></div></div>{error&&<p className="badge bad">{error}</p>}<div className="panel table-wrap"><table><thead><tr><th>User</th><th>Discord ID</th><th>Role</th><th>Status</th><th>Joined</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.global_name||x.username}</strong></td><td>{x.discord_id}</td><td><span className="badge">{x.role}</span></td><td>{x.status}</td><td>{new Date(x.joined).toLocaleDateString()}</td><td>{x.last_login?new Date(x.last_login).toLocaleString():'Never'}</td><td style={{display:'flex',gap:6}}>{x.status==='Active'?<button className="btn danger" onClick={()=>status(x.id,'Suspended')}>Suspend</button>:<button className="btn" onClick={()=>status(x.id,'Active')}>Unsuspend</button>}<button className="btn danger" onClick={()=>status(x.id,'Banned')}>Ban</button></td></tr>)}</tbody></table></div></div>
}

function PlexAdmin() {
 const [connection,setConnection]=useState<any>(null),[libs,setLibs]=useState<any[]>([]),[scans,setScans]=useState<any[]>([]),[error,setError]=useState('')
 const load=async()=>{try{const [c,l,s]=await Promise.all([api('/api/plex/connection'),api<any[]>('/api/plex/libraries'),api<any[]>('/api/plex/scans')]);setConnection(c);setLibs(l);setScans(s)}catch(e:any){setError(e.message)}}; useEffect(()=>{void load()},[])
 async function discover(){try{await api('/api/plex/libraries/discover',{method:'POST'});load()}catch(e:any){setError(e.message)}}
 async function toggle(lib:any){await api(`/api/plex/libraries/${lib.id}`,{method:'PATCH',body:JSON.stringify({enabled:!lib.enabled})});load()}
 async function scan(id:number){await api(`/api/plex/libraries/${id}/scan`,{method:'POST'});load()}
 return <div className="page"><div className="section-head"><div><h2>Plex & scans</h2><div className="muted">Server-side connectivity, exposed libraries and background indexing.</div></div><button className="btn" onClick={discover}>Discover libraries</button></div>{error&&<p className="badge bad">{error}</p>}<div className="grid-stats"><div className="stat"><span className="muted">Plex</span><strong style={{fontSize:18}}>{connection?.connected?'Connected':'Disconnected'}</strong></div><div className="stat"><span className="muted">Server</span><strong style={{fontSize:18}}>{connection?.server_name||'—'}</strong></div><div className="stat"><span className="muted">Version</span><strong style={{fontSize:18}}>{connection?.version||'—'}</strong></div><div className="stat"><span className="muted">Libraries enabled</span><strong>{libs.filter(x=>x.enabled).length}</strong></div></div><div className="section-head"><h2>Libraries</h2></div><div className="panel table-wrap"><table><thead><tr><th>Library</th><th>Type</th><th>Enabled</th><th>Last scan</th><th/></tr></thead><tbody>{libs.map(lib=><tr key={lib.id}><td><strong>{lib.title}</strong></td><td>{lib.type}</td><td><button className={`badge ${lib.enabled?'good':''}`} onClick={()=>toggle(lib)}>{lib.enabled?'Enabled':'Disabled'}</button></td><td>{lib.last_scan_at?new Date(lib.last_scan_at).toLocaleString():'Never'}</td><td><button className="btn" disabled={!lib.enabled} onClick={()=>scan(lib.id)}>Run scan</button></td></tr>)}</tbody></table></div><div className="section-head"><h2>Recent scans</h2></div><ScanTable scans={scans}/></div>
}

function ScanTable({scans}:{scans:any[]}) { return <div className="panel table-wrap"><table><thead><tr><th>Job</th><th>Library</th><th>Mode</th><th>Status</th><th>Scanned</th><th>+ / ~ / −</th><th>Finished</th></tr></thead><tbody>{scans.map(x=><tr key={x.id}><td>#{x.id}</td><td>{x.library_id}</td><td>{x.mode}</td><td><span className={`badge ${x.status==='completed'?'good':x.status==='failed'?'bad':'warn'}`}>{x.status}</span></td><td>{x.items_scanned}</td><td>{x.items_added} / {x.items_updated} / {x.items_removed}</td><td>{x.finished_at?new Date(x.finished_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div> }

function Logs() { const [rows,setRows]=useState<any[]>([]);useEffect(()=>{api<any[]>('/api/audit').then(setRows)},[]);return <div className="page"><div className="section-head"><h2>Audit logs</h2></div><div className="panel table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Actor</th><th>Target</th><th>IP</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.event}</td><td>{x.actor_user_id??'system'}</td><td>{x.target_type?`${x.target_type}:${x.target_id}`:'—'}</td><td>{x.ip||'sanitized'}</td></tr>)}</tbody></table></div></div> }

function ProtectedApp() {
 const [user,setUser]=useState<User|null|undefined>(undefined)
 useEffect(()=>{api<User>('/api/auth/me').then(setUser).catch(()=>setUser(null))},[])
 if(user===undefined)return <div className="page"><div className="skeleton" style={{height:400}}/></div>; if(user===null)return <Navigate to="/login" replace/>
 return <Shell user={user}><Routes><Route path="/browse" element={<Browse/>}/><Route path="/search" element={<Browse/>}/><Route path="/collections" element={<Browse/>}/><Route path="/movie/:id" element={<MovieDetail/>}/><Route path="/admin" element={<AdminDashboard/>}/><Route path="/admin/invites" element={<InviteAdmin user={user}/>}/><Route path="/admin/users" element={<UsersAdmin/>}/><Route path="/admin/plex" element={<PlexAdmin/>}/><Route path="/admin/logs" element={<Logs/>}/><Route path="*" element={<Navigate to="/browse" replace/>}/></Routes></Shell>
}

export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/invite/:token" element={<InvitePage/>}/><Route path="/*" element={<ProtectedApp/>}/></Routes>}